from classes.char_class import Class
from classes.barbarian import Barbarian
from classes.bard import Bard
from classes.cleric import Cleric
from classes.druid import Druid
from classes.fighter import Fighter
from classes.monk import Monk
from classes.paladin import Paladin
from classes.ranger import Ranger
from classes.rogue import Rogue
from classes.sorcerer import Sorcerer
from classes.warlock import Warlock
from classes.wizard import Wizard
